using System;
using System.Data.Entity.ModelConfiguration;
using System.Data.Entity.ModelConfiguration.Configuration;
using System.Linq.Expressions;
using Vinaday.Data.Models;

namespace Vinaday.Data.Models.Mapping
{
	public class HotelMap : EntityTypeConfiguration<Hotel>
	{
		public HotelMap()
		{
			HasKey(t => t.Id);
			Property(t => t.Name).IsRequired().HasMaxLength(250);
			Property(t => t.Country).HasMaxLength(255);
			Property(t => t.CITY).HasMaxLength(255);
			Property(t => t.HotelName).IsRequired().HasMaxLength(250);
			Property(t => t.Url).HasMaxLength(250);
			Property(t => t.StreetAddressEnglish).HasMaxLength(250);
			Property(t => t.StreetAddressLocal).HasMaxLength(250);
			Property(t => t.Phone).IsRequired().HasMaxLength(250);
			Property(t => t.Fax).HasMaxLength(250);
			Property(t => t.StateProvince).HasMaxLength(250);
			Property(t => t.PostCode).HasMaxLength(250);
			Property(t => t.HotelChain).HasMaxLength(250);
			Property(t => t.HotelBrand).HasMaxLength(250);
			Property(t => t.AccommodationtypeId).HasMaxLength(250);
			Property(t => t.Website).HasMaxLength(250);
			Property(t => t.HotelPicture1).HasMaxLength(250);
			Property(t => t.HotelPicture2).HasMaxLength(250);
			Property(t => t.HotelPicture3).HasMaxLength(250);
			Property(t => t.HotelPicture4).HasMaxLength(250);
			Property(t => t.HotelPicture5).HasMaxLength(250);
			Property(t => t.CheckIn).HasMaxLength(50);
			Property(t => t.CheckOut).HasMaxLength(50);
			Property(t => t.EarliestCheckIn).HasMaxLength(50);
			Property(t => t.Overview).HasMaxLength(500);
			Property(t => t.RatesCurrency).HasMaxLength(255);
			Property(t => t.RoomService).HasMaxLength(50);
			Property(t => t.RoomVoltage).HasMaxLength(250);
			Property(t => t.TimeToAirport).HasMaxLength(250);
			Property(t => t.YearHotelBuilt).HasMaxLength(50);
			Property(t => t.YearHotelLastRenovated).HasMaxLength(50);
			Property(t => t.HotelStyle).HasMaxLength(250);
			Property(t => t.HotelFacilities).HasMaxLength(250);
			Property(t => t.HotelRoomFacilities).HasMaxLength(250);
			Property(t => t.HotelSportRecreation).HasMaxLength(250);
			Property(t => t.HotelAbbrName).HasMaxLength(255);
			Property(t => t.HotelOtherName).HasMaxLength(500);
			Property(t => t.HotelKeyword).HasMaxLength(1000);
			Property(t => t.HotelStyle).HasMaxLength(50);
			Property(t => t.HotelNameLocal).HasMaxLength(255);
			Property(t => t.HotelNameDesc).HasMaxLength(500);
			Property(t => t.HotelAnotherName).HasMaxLength(500);
			Property(t => t.DistanceFromMainCity).HasMaxLength(50);
			Property(t => t.RegisterFormComplete).HasMaxLength(50);
			Property(t => t.HotelPolicy).HasMaxLength(1500);
			Property(t => t.CancelPolicyValue1).HasMaxLength(500);
			Property(t => t.CancelPolicyValue2).HasMaxLength(500);
			Property(t => t.CancelPolicyvalue1Vn).HasMaxLength(500);
			Property(t => t.CancelPolicyvalue2Vn).HasMaxLength(500);
			Property(t => t.SeoTitle).HasMaxLength(1000);
			Property(t => t.VnUrl).HasMaxLength(250);
			Property(t => t.SeoDescVn).HasMaxLength(400);
			Property(t => t.SeoTitleVn).HasMaxLength(400);
			Property(t => t.SeoDesc).HasMaxLength(400);
			Property(t => t.KeywordVn).HasMaxLength(1000);
			ToTable("HOTEL");
			Property(t => t.Id).HasColumnName("HOTELID");
			Property(t => t.Name).HasColumnName("NAME");
			Property(t => t.Description).HasColumnName("DESCRIPTION");
			Property(t => t.Country).HasColumnName("COUNTRY");
			Property(t => t.CountryId).HasColumnName("COUNTRYID");
			Property(t => t.CITY).HasColumnName("CITY");
			Property(t => t.KeyValue).HasColumnName("KeyValue");
			Property(t => t.CityId).HasColumnName("CITYID");
			Property(t => t.HotelName).HasColumnName("HOTELNAME");
			Property(t => t.Url).HasColumnName("URL");
			Property(t => t.MaincontractId).HasColumnName("MAINCONTRACTID");
			Property(t => t.ReservationcontractId).HasColumnName("RESERVATIONCONTRACTID");
			Property(t => t.MarketingcontractId).HasColumnName("MARKETINGCONTRACTID");
			Property(t => t.AccountcontractId).HasColumnName("ACCOUNTCONTRACTID");
			Property(t => t.StreetAddressEnglish).HasColumnName("STREETADDRESSENGLISH");
			Property(t => t.StreetAddressLocal).HasColumnName("STREETADDRESSLOCAL");
			Property(t => t.Phone).HasColumnName("PHONE");
			Property(t => t.Fax).HasColumnName("FAX");
			Property(t => t.StateProvince).HasColumnName("STATE_PROVINCE");
			Property(t => t.PostCode).HasColumnName("POST_CODE");
			Property(t => t.HotelChain).HasColumnName("HOTEL_CHAIN");
			Property(t => t.HotelBrand).HasColumnName("HOTEL_BRAND");
			Property(t => t.AccommodationtypeId).HasColumnName("ACCOMMODATIONTYPEID");
			Property(t => t.StartRating).HasColumnName("START_RATING");
			Property(t => t.NumberOfRoom).HasColumnName("NUMBEROFROOM");
			Property(t => t.Website).HasColumnName("WEBSITE");
			Property(t => t.Latitude).HasColumnName("LATITUDE");
			Property(t => t.Longtitude).HasColumnName("LONGTITUDE");
			Property(t => t.HotelPicture1).HasColumnName("HOTELPICTURE1");
			Property(t => t.HotelPicture2).HasColumnName("HOTELPICTURE2");
			Property(t => t.HotelPicture3).HasColumnName("HOTELPICTURE3");
			Property(t => t.HotelPicture4).HasColumnName("HOTELPICTURE4");
			Property(t => t.HotelPicture5).HasColumnName("HOTELPICTURE5");
			Property(t => t.AirportTransferAvailable).HasColumnName("AIRPORT_TRANSFER_AVAILABLE");
			Property(t => t.ShowAirportTransferAvailable).HasColumnName("SHOW_AIRPORT_TRANSFER_AVAILABLE");
			Property(t => t.AirportTransferFee).HasColumnName("AIRPORT_TRANSFER_FEE");
			Property(t => t.ShowAirportTransferFee).HasColumnName("SHOW_AIRPORT_TRANSFER_FEE");
			Property(t => t.BreakfastCharge).HasColumnName("BREAKFAST_CHARGE");
			Property(t => t.ShowBreakfastCharge).HasColumnName("SHOW_BREAKFAST_CHARGE");
			Property(t => t.CheckIn).HasColumnName("CHECK_IN");
			Property(t => t.ShowCheckIn).HasColumnName("SHOW_CHECK_IN");
			Property(t => t.CheckOut).HasColumnName("CHECK_OUT");
			Property(t => t.ShowCheckOut).HasColumnName("SHOW_CHECK_OUT");
			Property(t => t.EarliestCheckIn).HasColumnName("EARLIEST_CHECK_IN");
			Property(t => t.ShowEarliestCheckIn).HasColumnName("SHOW_EARLIEST_CHECK_IN");
			Property(t => t.NumberOfRestaurants).HasColumnName("NUMBER_OF_RESTAURANTS");
			Property(t => t.ShowNumberOfRestaurants).HasColumnName("SHOW_NUMBER_OF_RESTAURANTS");
			Property(t => t.Overview).HasColumnName("OVERVIEW");
			Property(t => t.NumberOfFloors).HasColumnName("NUMBEROFFLOORS");
			Property(t => t.RatesFrom).HasColumnName("RATES_FROM");
			Property(t => t.RatesCurrency).HasColumnName("RATES_CURRENCY");
			Property(t => t.ParkingAvailable).HasColumnName("PARKING_AVAILABLE");
			Property(t => t.ShowParkingAvailable).HasColumnName("SHOW_PARKING_AVAILABLE");
			Property(t => t.RoomService).HasColumnName("ROOM_SERVICE");
			Property(t => t.ShowRoomService).HasColumnName("SHOW_ROOM_SERVICE");
			Property(t => t.RoomVoltage).HasColumnName("ROOM_VOLTAGE");
			Property(t => t.ShowRoomVoltage).HasColumnName("SHOW_ROOM_VOLTAGE");
			Property(t => t.TimeToAirport).HasColumnName("TIME_TO_AIRPORT");
			Property(t => t.ShowTimeToAirport).HasColumnName("SHOW_TIME_TO_AIRPORT");
			Property(t => t.YearHotelBuilt).HasColumnName("YEAR_HOTEL_BUILT");
			Property(t => t.HashTagEn).HasColumnName("HashTagEn");
			Property(t => t.HashTagVn).HasColumnName("HashTagVn");
			Property(t => t.ShowYearHotelBuilt).HasColumnName("SHOW_YEAR_HOTEL_BUILT");
			Property(t => t.YearHotelLastRenovated).HasColumnName("YEAR_HOTEL_LAST_RENOVATED");
			Property(t => t.ShowYearHotelLastRenovated).HasColumnName("SHOW_YEAR_HOTEL_LAST_RENOVATED");
			Property(t => t.NumberOfReview).HasColumnName("NUMBER_OF_REVIEW");
			Property(t => t.RatingAverage).HasColumnName("RATING_AVERAGE");
			Property(t => t.Status).HasColumnName("STATUS");
			Property(t => t.HotelStyle).HasColumnName("HOTEL_STYLE");
			Property(t => t.HotelFacilities).HasColumnName("HOTEL_FACILITIES");
			Property(t => t.HotelRoomFacilities).HasColumnName("HOTEL_ROOM_FACILITIES");
			Property(t => t.HotelSportRecreation).HasColumnName("HOTEL_SPORT_RECREATION");
			Property(t => t.HotelAbbrName).HasColumnName("HOTEL_ABBR_NAME");
			Property(t => t.HotelOtherName).HasColumnName("HOTEL_OTHER_NAME");
			Property(t => t.HotelKeyword).HasColumnName("HOTEL_KEYWORD");
			Property(t => t.HotelStyleName).HasColumnName("HOTEL_STYLE_NAME");
			Property(t => t.HotelNameLocal).HasColumnName("HOTEL_NAME_LOCAL");
			Property(t => t.HotelNameLocalDesc).HasColumnName("HOTEL_NAME_LOCAL_DESC");
			Property(t => t.HotelNameDesc).HasColumnName("HOTEL_NAME_DESC");
			Property(t => t.ImageId).HasColumnName("IMAGE_ID");
			Property(t => t.HotelAnotherName).HasColumnName("HOTEL_ANOTHER_NAME");
			Property(t => t.DistanceFromMainCity).HasColumnName("DISTANCE_FROM_MAIN_CITY");
			Property(t => t.ShowDistanceFromManCity).HasColumnName("SHOW_DISTANCE_FROM_MAN_CITY");
			Property(t => t.RegisterFormComplete).HasColumnName("REGISTERFORMCOMPLETE");
			Property(t => t.RegisterPercentage).HasColumnName("REGISTERPERCENTAGE");
			Property(t => t.HotelPolicy).HasColumnName("HOTELPOLICY");
			Property(t => t.Currency).HasColumnName("CURRENCY");
			Property(t => t.CancelPolicyValue1).HasColumnName("CANCELPOLICYVALUE1");
			Property(t => t.CancelPolicyValue2).HasColumnName("CANCELPOLICYVALUE2");
			Property(t => t.CancelPolicyType).HasColumnName("CANCELPOLICYTYPE");
			Property(t => t.CancelpolicyFromDay).HasColumnName("CANCELPOLICY_FROMDAY");
			Property(t => t.CancelpolicyToday).HasColumnName("CANCELPOLICY_TODAY");
			Property(t => t.CancelPolicyvalue1Vn).HasColumnName("CANCELPOLICYVALUE1_VN");
			Property(t => t.CancelPolicyvalue2Vn).HasColumnName("CANCELPOLICYVALUE2_VN");
			Property(t => t.SeoTitle).HasColumnName("Seo_Title");
			Property(t => t.VnUrl).HasColumnName("vn_url");
			Property(t => t.SeoDescVn).HasColumnName("Seo_desc_vn");
			Property(t => t.SeoTitleVn).HasColumnName("Seo_Title_vn");
			Property(t => t.SeoDesc).HasColumnName("Seo_desc");
			Property(t => t.IsClub).HasColumnName("IsClub");
			Property(t => t.ClubContent).HasColumnName("ClubContent");
			Property(t => t.ClubIncentives).HasColumnName("ClubIncentives");
			Property(t => t.KeywordVn).HasColumnName("KeywordVN");
			Property(t => t.IsSeo).HasColumnName("IsSeo");
			Property(t => t.RegionId).HasColumnName("RegionId");
			Property(t => t.CollectionValue).HasColumnName("CollectionValue");
			HasRequired(t => t.Contact).WithMany(t => t.Hotels).HasForeignKey(d => d.MaincontractId);
			HasOptional(t => t.Contact1).WithMany(t => t.Hotels1).HasForeignKey(d => d.AccountcontractId);
			HasOptional(t => t.Contact2).WithMany(t => t.Hotels2).HasForeignKey(d => d.MarketingcontractId);
			HasOptional(t => t.Contact3).WithMany(t => t.Hotels3).HasForeignKey(d => d.ReservationcontractId);
			HasOptional(t => t.Country1).WithMany(t => t.Hotels1).HasForeignKey(d => d.CountryId);
			HasOptional(t => t.Image).WithMany(t => t.Hotels).HasForeignKey(d => d.ImageId);
			HasOptional(t => t.RateOfExchange).WithMany(t => t.Hotels).HasForeignKey(d => d.Currency);
		}
	}
}